# Generated by Django 5.1.1 on 2024-10-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0004_itenscompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenscompra',
            name='preco_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
